project_id = "zndyokpudijoidropdou"

[functions.analyze-screenshot]
verify_jwt = false

[functions.parse-text]
verify_jwt = false

[functions.recommend-card]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.analyze-points-screenshot]
verify_jwt = false

[functions.send-points-email]
verify_jwt = false
